= ST3-Moderator

ST3-Moderator is a discord bot programmed by @ST3VI3 RICHI3#5015, the bot was created with moderation in mind.
The current version of the bot is not the first write. ST3-Moderator had a previous life in whitch it ran 24/7. The previous bot died due to hard drive faliure. This bot, hopefully, will not fail in the same way.


The bot aims to ease discord server moderation. This will be achived by not only alowing customisation (from self-hosted versions) but providing utilities such as spam protection (Not currently implemented), timed user mutes (Not currently implemented), etc.


The bot can be added link:https://discordapp.com/api/oauth2/authorize?client_id=459014792464695317&permissions=8&scope=bot[here].

Current bot features::
    Dev:::
        * Configuration
        ** Config:: Configures a property within a given JSON file. +
        Args: "module", "property", "value", "file" (Optional). A list can be provided at each stage, pass "*" if module only.
        * Cogs
        ** Cog_Load:: Loads all cogs or loads a given cog. +
        Args: "*Cog" - Cog is the cog to load, referenced via "Commands.{Cog}" (EG: "Commands.Help"). "*" may be past to load all cogs.
        ** Cog_Reload:: Reloads all cogs or reloads a given cog. +
        Args: "*Cog" - Cog is the cog to load, referenced via "Commands.{Cog}" (EG: "Commands.Help"). "*" may be past to reload all cogs.
        ** Cog_Unload:: Unloads all cogs or unloads a given cog. +
        Args: "*Cog" - Cog is the cog to load, referenced via "Commands.{Cog}" (EG: "Commands.Help"). "*" may be past to Unload all cogs.
        * Remote Control
        ** Update:: Updates the bot via this git repository +
        Args: None
        ** Restart:: Restarts the bot +
        Args: None
        ** Shutdown:: Causes the script to exit +
        Args: None